name: Update Nginx Config

on:
  workflow_dispatch:

jobs:
  update-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy nginx.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "nginx.conf"
          target: "/tmp/nginx.conf"

      - name: Backup, replace, and reload Nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Backup current config
            sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak.$(date +%F-%T)
            # Replace with new config
            sudo mv /tmp/nginx.conf /etc/nginx/nginx.conf
            # Validate and reload
            sudo nginx -t && sudo systemctl reload nginx
