# .github/workflows/ssm.yml
name: Test SSM Access

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:

jobs:
  ssm-command:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::440436437688:role/GitHubSSMRole
          aws-region: ap-south-1

      - name: Run command on EC2 via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=i-0d95d6982863613cf" \
            --comment "GitHub triggered command" \
            --parameters 'commands=["mkdir SSM"]' \
            --region ap-south-1
