name: Deploy GST Chatbot

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install git if not present
            if ! command -v git &> /dev/null; then
              sudo yum install -y git
            fi

            # Install nvm and Node.js
            if ! command -v nvm &> /dev/null; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            fi
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            if ! command -v node &> /dev/null; then
              nvm install 16.14.0
            fi
            nvm use 16.14.0

            # Install pm2 if not present
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            if ! command -v redis-server &> /dev/null; then
              sudo dnf install -y redis6
              sudo systemctl enable --now redis6
            else
              echo "Redis is already installed."
              sudo systemctl start redis6
              sudo systemctl enable redis6
            fi
            sudo systemctl status redis6
            

            rm -rf /tmp/botkit-repo
            git clone https://github.com/saikumar7817/Node.js-Chatbot-app.git /tmp/botkit-repo

            sudo mkdir -p /usr/bin/triva_chatbot/botkit
            sudo chown $USER:$USER /usr/bin/triva_chatbot/botkit

            cp -r /tmp/botkit-repo/botkit/* /usr/bin/triva_chatbot/botkit/

            rm -rf /tmp/botkit-repo
            
            cd /usr/bin/triva_chatbot/botkit/casetext
            pm2 start app.js --name "casetext_app"



